alias sourcetree='open -a SourceTree'
alias br='browse-repository'

alias gs='git status'
alias ga='git add .'
alias gb='git branch'
alias gba='git branch -a'
alias gc='git commit'
alias gcm='git commit -m'
alias go='git checkout '
alias ghistory='git log --graph --oneline --decorate --all'
